# Generated by Django 3.2.5 on 2021-08-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_newproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproduct',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
