# Generated by Django 3.2.5 on 2021-08-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_newproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproduct',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
